disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Zona Karier"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "blowfish_logo.png"
description = "Zona Karier adalah platform untuk mencari lowongan pekerjaan, magang, pelatihan, sertifikasi, dan informasi karier melalui artikel blog yang bermanfaat untuk persiapan kerja"
secondaryLogo = "apple-touch-icon.png"

  [params.author]
  links = [ ]

["params.author"]
name = "Andre Yulianto"
image = "andre-yulianto.jpg"
headline = "Ini adalah headline profil author"
bio = "Ini adalah Bio Author"
