colorScheme = "blowfish"
defaultAppearance = "light"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
replyByEmail = false
disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false
fingerprintAlgorithm = "sha512"
giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v8.next.forgejo.org"
firebase = { }
fathomAnalytics = { }
umamiAnalytics = { }
selineAnalytics = { }
buymeacoffee = { }
verification = { }
rssnext = { }
advertisement = { }
defaultBackgroundImage = "."
defaultFeaturedImage = "tn.png"
highlightCurrentMenuArea = ""
smartTOC = true
smartTOCHideUnfocusedChildren = true

[header]
layout = "basic"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = false
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "page"
showRecent = true
showRecentItems = "12"
showMoreLink = ""
showMoreLinkDest = "/posts/"
cardView = true
cardViewScreenWidth = true
layoutBackgroundBlur = false
disableHeroImageFilter = false
homepageImage = "tn.png"

[article]
showDate = false
showViews = false
showLikes = false
showDateOnlyInArticle = false
showDateUpdated = false
showAuthor = false
showHero = true
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = "show"
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = false
invertPagination = false
showReadingTime = false
showTableOfContents = true
showTaxonomies = true
showCategoryOnly = false
showAuthorsBadges = true
showWordCount = false
showZenMode = false
heroStyle = ""
showRelatedContent = true
relatedContentLimit = ""

[list]
showHero = false
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = true
showSummary = true
showViews = false
showLikes = false
showTableOfContents = false
showCards = true
orderByWeight = false
groupByYear = true
cardView = false
cardViewScreenWidth = false
constrainItemsWidth = false
heroStyle = "basic"

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = false
cardView = false

[term]
showHero = false
showBreadcrumbs = true
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = true
cardViewScreenWidth = ""
